export const userInputs = [
  {
    id: 1,
    name: "fname",
    label: "First Name",
    type: "text",
    placeholder: "John",
  },
  {
    id: 2,
    name: "lname",
    label: "Last Name",
    type: "text",
    placeholder: "Doe",
  },
  {
    id: 3,
    name: "contact",
    label: "Contact",
    type: "text",
    placeholder: "+1 234 567 89",
  },
  {
    id: 4,
    name: "address",
    label: "Address",
    type: "text",
    placeholder: "Elton St. 216 NewYork",
  },
  {
    id: 5,
    name: "username",
    label: "Username",
    type: "text",
    placeholder: "john_doe",
  },
  {
    id: 6,
    name: "email",
    label: "Email",
    type: "email",
    placeholder: "john_doe@gmail.com",
  },
  {
    id: 7,
    name: "password",
    label: "Password",
    type: "password",
  },
  {
    id: 8,
    name: "cpassword",
    label: "Confirm Password",
    type: "password",
  },
];

export const bookingInputs = [
  {
    id: 1,
    name: "event",
    label: "Booking Event",
    type: "text",
    placeholder: "Event..",
  },
  {
    id: 2,
    name: "timing",
    label: "Time Duration",
    type: "multiselect",
    options: [
      { value: "morning", label: "Morning" },
      { value: "afternoon", label: "Afternoon" },
      { value: "evening", label: "Evening" },
    ],
  },
  {
    id: 3,
    name: "price",
    label: "Price",
    type: "number",
    placeholder: "2000",
  },
  {
    id: 4,
    name: "eventDate",
    label: "Date",
    type: "date",
  },
  {
    id: 5,
    name: "custName",
    label: "Customer Name",
    type: "text",
    placeholder: "John Doe",
  },
  {
    id: 6,
    name: "address",
    label: "Address",
    type: "text",
    placeholder: "Elton St. 216 NewYork",
  },
  {
    id: 7,
    name: "contact",
    label: "Contact",
    type: "number",
    placeholder: "+977 9841763684",
  },
];
